name: Self Hosted Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: ./full-test.sh
        
      - name: Run unit tests
        run: ./unit-test.sh
